QPID-8170: fix exception string from qpid_tests.broker_1_0 tests running against amqp0-10 broker
Issue was originally introduced in QPID-5836.

```
qpid_tests.broker_1_0.general.GeneralTests.test_anonymous_relay ... fail
Error during setup:  Traceback (most recent call last):
    File "qpid-python-test", line 347, in run
      phase()
    File "/home/jdanek/repos/qpid/qpid-python/qpid/tests/messaging/__init__.py", line 49, in setup
      self.conn = self.setup_connection()
    File "/home/jdanek/repos/qpid/qpid-python/qpid/tests/messaging/__init__.py", line 207, in setup_connection
      return self.create_connection()
    File "/home/jdanek/repos/qpid/qpid-python/qpid/tests/messaging/__init__.py", line 204, in create_connection
      return Connection.establish(self.broker, **opts)
    File "/home/jdanek/repos/qpid/qpid-python/qpid/messaging/endpoints.py", line 111, in establish
      conn = Connection(url, **options)
    File "/home/jdanek/repos/qpid/qpid-python/qpid/messaging/endpoints.py", line 209, in __init__
      raise ConnectionError("Connection option 'protocol' value '" + value + "' unsupported (must be amqp0-10)")
  TypeError: cannot concatenate 'str' and 'bool' objects
```