QPID-8170: fix qpid_tests.broker_0_10.management.ManagementTest.test_reroute_queue
```
qpid_tests.broker_0_10.management.ManagementTest.test_reroute_queue ... fail
Error during test:  Traceback (most recent call last):
    File "qpid-python-test", line 347, in run
      phase()
    File "/home/jdanek/repos/qpid/qpid-python/qpid_tests/broker_0_10/management.py", line 346, in test_reroute_queue
      url = "%s://%s:%d" % (self.broker.scheme or "amqp", self.broker.host, self.broker.port)
  TypeError: %d format: a number is required, not NoneType
```